package com.cont.commands.users;

import org.apache.commons.lang3.RandomStringUtils;
import org.apache.commons.lang3.StringUtils;

import com.cont.commands.ResultCommandInterface;
import com.cont.controllers.exceptions.UnprocessableEntityException;
import com.cont.models.api.User;
import com.cont.models.entities.UserEntity;
import com.cont.models.repositories.UserRepository;
import com.cont.models.repositories.interfaces.UserRepositoryInterface;

public class UserCreateCommand implements ResultCommandInterface<User> {
	@Override
	public User execute() {
		//Validations
		if (StringUtils.isBlank(this.apiUser.getFirstName())) {
			throw new UnprocessableEntityException("first name");
		}
		if (StringUtils.isBlank(this.apiUser.getLastName())) {
			throw new UnprocessableEntityException("last name");
		}
		if (StringUtils.isBlank(this.apiUser.getPassword())) {
			throw new UnprocessableEntityException("password");
		}
		
		//Generate a numeric User ID of length User_ID_LENGTH for the new User,
		// making sure that the User ID is not already assigned to another User.
		// This field is distinct from the record ID.
		String newUserId;
		do {
			newUserId = RandomStringUtils.randomNumeric(User_ID_LENGTH);
		} while (this.UserRepository.userIdExists(newUserId));

		this.apiUser.setUserId(newUserId);

		UserEntity UserEntity = new UserEntity(this.apiUser); //Create a new ENTITY object from the API object details.
		UserEntity.save(); //Write, via an INSERT, the new record to the database.
		
		this.apiUser.setId(UserEntity.getId()); //Synchronize information generated by the database upon INSERT.
		this.apiUser.setCreatedOn(UserEntity.getCreatedOn());
		this.apiUser.setPassword(StringUtils.EMPTY); //Only send the password over the network when modifying the database.
		
		return this.apiUser;
	}
	
	//Properties
	private User apiUser;
	public User getApiUser() {
		return this.apiUser;
	}
	public UserCreateCommand setApiUser(User apiUser) {
		this.apiUser = apiUser;
		return this;
	}
	
	private UserRepositoryInterface UserRepository;
	public UserRepositoryInterface getUserRepository() {
		return this.UserRepository;
	}
	public UserCreateCommand setUserRepository(UserRepositoryInterface UserRepository) {
		this.UserRepository = UserRepository;
		return this;
	}
	
	private static final int User_ID_LENGTH = 4;
	
	public UserCreateCommand() {
		this.UserRepository = new UserRepository();
	}
}
